# Generated by Django 3.1.7 on 2021-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='rating',
            field=models.FloatField(default=1),
        ),
    ]
